### ISSUE TITLE
Increase MaxScriptElementSize in txscript package

### ISSUE THREAD

**Issue by rohenaz** [bitcoinsv/bsvd#1]
Recently, a transaction with 17kb of OP_RETURN data was mined by coingeek.
https://blockchair.com/bitcoin-sv/address/d-3f5c7cbe8927da73271dba9c1bc1abb4

If this is going to become a thing, txscript pkg will need updating. Not sure what the new limit will be if any.

To test, I changed script.go line 46 from a value of 520, to 20520
`MaxScriptElementSize  = 20520 // Max bytes pushable to the stack.`

This was all that was required to generate a large tx. Not sure what is required for broadcasting, or what else would be effected as I'm using this for tx utils, not running a node.

**Comment by shilch** [comment]
Thanks! I will definitely keep an eye on it.

**Comment by rohenaz** [comment]
looks like the new datacarriersize=100000
this includes opcodes

**Comment by shilch** [comment]
Perfect, do you mind creating a PR and reference this issue?

**Comment by rohenaz** [comment]
np

**Comment by shilch** [comment]
Closed with #2
